package com.xhg.test.image;

import android.graphics.Bitmap;
import android.os.AsyncTask;
import android.util.Log;

import com.xhg.test.image.strategies.ColorStrategy;
import com.xhg.test.image.strategies.Mandelbrot1;
import com.xhg.test.image.strategies.Mandelbrot3;

import java.util.concurrent.atomic.AtomicInteger;

/**
 * @author xionghg
 * @email xiong9394@gmail.com
 * @created 2017-07-04.
 */

public class ColorHolder {

    public static final int CPU_COUNT = Runtime.getRuntime().availableProcessors();
    private static final String TAG = "ColorHolder";
    private static final int PARALLEL_COUNT = Math.max(2, Math.min(CPU_COUNT - 1, 8));

    private int mHeight;
    private int mWidth;
    private ColorStrategy mStrategy;
    private Callback mCallback;
    private int[] mColorArray;
    private int mAlpha = 0xff << 24;
    private final AtomicInteger resultCount = new AtomicInteger(0);
    private final AtomicInteger successCount = new AtomicInteger(0);
    private volatile Status mStatus = Status.PENDING;
    private int[] mProgress;

    public ColorHolder() {
        this(1024, 1024);
    }

    public ColorHolder(int width, int height) {
        if (numberWrong(width) || numberWrong(height)) {
            throw new IllegalArgumentException("params not right");
        }
        this.mWidth = width;
        this.mHeight = height;
        mColorArray = new int[width * height];
    }

    private boolean numberWrong(int number) {
        return (number <= 0 || number > 10000);
    }

    /**
     * Create a bitmap using the color array created.
     *
     * @return Null if mStatus is not Status.FINISHED, always call this method in CallBack
     */
    public Bitmap createBitmap() {
        if (mStatus != Status.FINISHED) {
            return null;
        }
        return Bitmap.createBitmap(mColorArray, mWidth, mHeight, Bitmap.Config.ARGB_8888);
    }

    private void updateProgress(int index, int progress) {
        if (mCallback != null) {
            mProgress[index] = progress;
            int current = 0;
            int total = 0;
            for (int p : mProgress) {
                current += p;
                total += 100;
            }
            mCallback.onProgressUpdate(current * 100 / total);
        }
    }

    private void createColorFinish() {
        Log.d(TAG, "create color finish: ");
        mStatus = Status.FINISHED;
        if (mCallback != null) {
            if (successCount.get() == PARALLEL_COUNT) {
                mCallback.onProgressUpdate(100);
                mCallback.onColorsCreated();
            }
        }
        resultCount.set(0);
        successCount.set(0);
    }

    private void start(boolean inParallel) {
        Log.d(TAG, "create color start: cpu_count=" + CPU_COUNT);
        mStatus = Status.RUNNING;
        if (mStrategy == null) {
            // Initialize a strategy if not specified
            mStrategy = new Mandelbrot1();
        }
        if (mCallback != null) {
            mCallback.onStart();
        }

        if (inParallel) {
            mProgress = new int[PARALLEL_COUNT];
            int begin;
            int end = 0;
            for (int i = 1; i <= PARALLEL_COUNT; i++) {
                begin = end;
                end = mHeight * i / PARALLEL_COUNT;
                // Log.d(TAG, "start in parallel, begin=" + begin + " end=" + end);
                new MyAsyncTask(i - 1, "AsyncTask#" + i).executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR, begin, end);
            }
        } else {
            mProgress = new int[1];
            // Log.d(TAG, "start in serial, begin=0 end=" + mHeight);
            new MyAsyncTask(0, "AsyncTask#Single").execute(0, mHeight);
        }
    }

    public void startInParallel() {
        start(mHeight > 300 || mColorArray.length > 100000);
    }

    public void startInSerial() {
        start(false);
    }

    public int getHeight() {
        return mHeight;
    }

    public void setHeight(int height) {
        mHeight = height;
    }

    public int getWidth() {
        return mWidth;
    }

    public void setWidth(int width) {
        mWidth = width;
    }

    public ColorStrategy getStrategy() {
        return mStrategy;
    }

    public ColorHolder setStrategy(ColorStrategy strategy) {
        mStrategy = strategy;
        return this;
    }

    public Callback getCallback() {
        return mCallback;
    }

    public ColorHolder setCallback(Callback callback) {
        mCallback = callback;
        return this;
    }

    /**
     * Cause mColorArray is generated by ColorStrategy, so there is no
     * setColorArray() method, use setStrategy() instead.
     *
     * @return mColorArray
     */
    public int[] getColorArray() {
        return mColorArray;
    }

    public int getAlpha() {
        return mAlpha;
    }

    /**
     * Set the alpha value for the Bitmap if you want
     */
    public void setAlpha(int alpha) {
        mAlpha = alpha;
    }

    /**
     * Indicates the current status of the holder.
     */
    public enum Status {
        /**
         * Indicates that the holder has not created colors yet.
         */
        PENDING,
        /**
         * Indicates that the holder is creating colors.
         */
        RUNNING,
        /**
         * Indicates that {@link ColorHolder#createBitmap} has finished.
         */
        FINISHED,
    }

    /**
     * Interface definition for a callback to be invoked when a view is clicked.
     */
    public interface Callback {
        /**
         * Called before generate colors, add this interface because we always want to do the
         * same things before start generate colors, like set Button to disable.
         */
        void onStart();

        /**
         * Called when progress updated..
         */
        void onProgressUpdate(int progress);

        /**
         * Called when colors has been created.
         */
        void onColorsCreated();
    }

    private class MyAsyncTask extends AsyncTask<Integer, Integer, Boolean> {
        private int mIndex = 0;
        private String mName = "AsyncTask";

        public MyAsyncTask(int index, String name) {
            super();
            mIndex = index;
            mName = name;
        }

        @Override
        protected Boolean doInBackground(Integer... params) {
            Log.d(TAG, mName + " doInBackground:");
            if (params.length < 2) {
                return false;
            }
            int start = params[0];
            int end = params[1];
            //单线程7.869s
            //2线程4.001s
            //3线程4.294s  3664 4405 4815
            //6线程1.773s  1761 1871 1688
            //7线程1.763s
            for (int j = start; j < end; j++) {
                for (int i = 0; i < mWidth; i++) {
                    //int r = mStrategy.getRed(i, j) % 256 << 16;
                    //int g = mStrategy.getGreen(i, j) % 256 << 8;
                    //int b = mStrategy.getBlue(i, j) % 256;
                    int rgb = mStrategy.getRGB(i, j);
                    mColorArray[j * mWidth + i] = mAlpha | rgb;
                }
                publishProgress(j, start, end);
            }
            if (mStrategy instanceof Mandelbrot3) {
                // 发现一个多线程问题，rcount > width * height
                Log.d(TAG, "doInBackground: getCount=" + ((Mandelbrot3) mStrategy).rcount.get() +
                        " " + ((Mandelbrot3) mStrategy).gcount );
            }
            return true;
        }

        @Override
        protected void onProgressUpdate(Integer... values) {
            int total = values[2] - values[1];
            int current = values[0] - values[1] + 1;
            updateProgress(mIndex, current * 100 / total);
        }

        @Override
        protected void onPostExecute(Boolean aBoolean) {
            Log.d(TAG, mName + " onPostExecute called");
            if (aBoolean) {
                successCount.getAndIncrement();
            }
            if (resultCount.incrementAndGet() == mProgress.length) {
                createColorFinish();
            }
        }
    }
}
